# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KidsTube' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KidsTube
  pod 'FMDB', '~> 2.7'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'AFNetworking', '~> 3.1'
  pod 'youtube-ios-player-helper', '~> 0.1'
  pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
  pod 'Google/SignIn', '~> 3.0.3'

  target 'KidsTubeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KidsTubeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
